import { Roboto } from "next/font/google";
import "./globals.css";

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "HARMONIA MEDICAL",
  // TODO: Change description and title
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
